### ISSUE TITLE
Spin out LDN into a chapter

### ISSUE THREAD

**Issue by rhiaro** [csarven/lr-thesis#11]
Or a major section in the decentralisation chapter.

It's an original contribution, so treat it like that rather than literature you're reviewing. eg. Notifications were missing from this stack of standards, so I added it.

It is a whole (award-winning) paper, worth including properly.

You can put the Linked Specs Test Suite stuff in this section too then.

**Comment by csarven** [comment]
The rough plan for LDN was for the chapter on social stuff. It is briefly mentioned in the other chapters. Would that still work or feeling that LDN / Test Suite papers should be on their own?

**Comment by csarven** [comment]
Moved it out.
