### ISSUE TITLE
Feedback for 'decentralisation' chapter

### ISSUE THREAD

**Issue by rhiaro** [csarven/lr-thesis#13]
* [x] Write an intro for the chapter. What are you setting out to do? Why? How does it fit into the bigger picture of the whole thesis?
* [x] What's the deal with the `<hr/s>`s?
* [x] Editorial notes in https://github.com/csarven/lr-thesis/pull/12
* See also: https://github.com/csarven/lr-thesis/issues/11

**Information Society**

* [x] "information society" definition - citation needed 
* [x] "inherently decentralised - with the exception of DNS" - citation needed
* [x] "Information control tends to happen through system designs that are inherently centralised." - citation needed
* [x] "For instance, an individual can expect to participate in exchanging knowledge and goods autonomously." <- what? in what context? why does anyone expect this?
* [x] "and interact with participants and information" -> who are participants? The public? Other researchers? Participants in what?
* [x] Last paragraph about what researchers can do with access to the Web is pie in the sky. There are way to many barriers to just flip a switch and have a 'global commons'. Should you be presenting this as an idealised view? Maybe "technologically speaking" this could be the case.
* [x] Conclusion / articulate point / summarise. What are you trying to tell us with this section exactly?

**Control Yourself**

* [x] Intro - this section introduces the concept of decentralisation on the Web, and the existing technologies that make it possible... etc. 
* [x] Add a (cited) definition of decentralisation. There are loads; I used a Harry Halpin one.
* [x] Section is generally mixed up, jumping between saying Web is too centralised and that Web can solve scholarly comm. through decentralisation. I think you need to make two points:
  * about need to re-decentralise the Web.
  * why doing so benefits scholarly communication.
  * Point out the situation is complicated; we need to improve decentralisation AND take further steps to apply it to scientific publishing.
* [x] "In a fully decentralised setting, each source is filterless and responsible for its own quality and reputation, while others are free to selectively (dis-)trust certain sources using any mechanism they desire." <- this is absolutely not making a positive case for decentralisation.
* [x] "which has the potential to engage more people sooner" <- why is sooner better?
* [x] "If we want to strengthen the decentralised nature of the Web again, we need to develop technologies to simplify the decentralised authoring, management, exploration, and search of Web content." <- this paragraph does not belong here. Maybe earlier?
* [x] "Any third-party involvement is fundamentally subject to conflict with that notion." <- I ~call bullshit~ thoroughly dispute the truth of this assertion.
* [x] "information silos" - citation
* [x] "data" and "applications" bullets - define what these are?
* [x] "applications for the status quo" <- what are these? what do you mean? citation?
* [x] "Hence, we strive towards neutrality and democratisation of scholarly knowledge on all levels of access for humans and machines; and decentralisation and decoupling of data and applications while addressing some of the infrastructure limitations and needs in order to conduct genuine scholarly communication on the Web." <- this is a bit manifesto. Is it meant to be a statement of intent for the chapter/thesis?
* [x] Ultimately, I read all that, and I don't really know what the point of that section was or what I learnt from it. Can you sum it up?

**Challenges..**

* [x] Why is there a bunch of scholarly ecosystem stuff in the middle of the decentralisation chapter? Herbert theory should be somewhere else.
* [x] Yeah most of this just needs moving. Tramp stuff needs to go somewhere with why centralisation is bad. Maybe the previous (control yourself) section.
* [x] Conclusion of Tramp and Sambra stuff here is that LD tech is good for this. Belongs in next (standards) section?
* [x] "While there are plethora of <cite>architecturally significant requirements</cite> that would be necessary to design a system that is sociotechnical in nature, meanwhile encouraging autonomous and interoperable participation on the open Web, we focus on non-functional and functional requirements in this thesis." <- what does this mean?!?!
* [x] Maybe your requirements bullets should go in the conclusion of this chapter, presented as derived from the standards you describe as background literature.

**Standards**

* [x] Write introduction.
* [x] "Standards for decentralised Web" is way too generic; maybe "interoperable applications"?
* [x] "However, Ted Nelson disputes this design choice with respect to the original Hypertext design." <- good for Ted, but I don't think this is relevant or useful here.
* [ ] Subheadings for each standard.
* [x] Feels like a weird amount of detail on HTTP, but you do you.
* [x] "legally"...?
* [x] Memento and WAC are mentioned in the Fedora paragraph, but not detailed yet.
* [x] WA needs an LDP reference I think.
* [x] Yes, re: "only annotation-protocol and maybe annotation-model should be here and the rest in structure-of-scholarly-communication?"
* [x] "The design pattern for these Linked Data centric read-write architectures" <- these bullets are a good summary but why are they in the middle of the list?? Put them at the end..

**Decentralised Storage**

* [x] I agree that flat is good, keep these sections separate (and potentially rename "standards..")
* [x] Maybe move before standards section, and emphasise separation of storage vs. apps. Follows on from earlier stuff.
* [x] Actually finish this section.

**Universal Identity**

* [x] Write an intro - why is this relevant for scholarly comms? Tie into earlier chapter. Attribution, reputation, trust etc.
* [x] Make the point somewhere that registering your own URI is an alternative to having identifiers assigned for you by a third party (like ORCID). Maybe as a lead in to WebID.
* [x] The technologies described here really need listing as standards in their own sections, as with previous ones, I think.
* [x] Desired qualities - frame as inferred from the prior list of existing stuff. Conclude with this.
* [x] Make a subsection called 'multiple identifiers' for your WebID+ORCID stuff. ie. here I provide a real life example of multiple identifiers held by an academic researcher (myself) and how they can be linked and interact.

**Authentication**

* [x] Maybe too much detail for Web of Trust?
* [x] Cert stuff seems slightly overkill too. Those code dumps did not look good on my kindle.
* [x] Not enough on OIDC though!

**Authorization**

* [x] Something is missing here. Not sure what.

**Persistence and Preservation**

* [x] Introduction: this section ties together identification and archiving (I think) making the connection to scholarly communication clear. Express that.

**Implementing..**

* [x] "a Read-Write Linked Data Web" is overselling it. Maybe "Implementing Linked Research"?
* [x] Maybe this needs spinning out into its own chapter. Especially as it ties in social and structure stuff too.
* [x] Intro: in this section we demonstrate how the various standards described in this chapter can be pieced together into an application designed for researchers to particpate in the scholarly communication ecosystem.

**Linked Specifciations..**

* [x] Extract into [LDN chapter](https://github.com/csarven/lr-thesis/issues/11)

**Effects and Artefacts**

* [x] This is a good concluding section. Add stuff to make it super clear it's a concluding section for the whole chapter.

**Comment by csarven** [comment]
Thanks. Mostly covered now I guess.
